### ISSUE TITLE
Can insert images

### ISSUE THREAD

**Issue by desaintflorent** [murdercode/Nova4-TinymceEditor#1]
Hi there, 

Can we insert images with your plugin ?

**Comment by murdercode** [comment]
Hi,
actually it supports only external images.
I will add directly upload in the future but actually there's no ETA.

**Comment by murdercode** [comment]
Coming soon an upgrade for image uploads
https://github.com/murdercode/Nova4-TinymceEditor/commit/2949ea8845a8bfd2cd300318887e80b0b252ffe8

Will be released in 1.1

**Comment by murdercode** [comment]
Released https://github.com/murdercode/Nova4-TinymceEditor/releases/tag/v1.1.0
