### ISSUE TITLE
Styling output

### ISSUE THREAD

**Issue by exshapoval** [murdercode/Nova4-TinymceEditor#14]
Hi

any information how to styling output content?

For example I add codesample plugin and in editor I see (code type php)

![iScreen Shoter - Google Chrome - 230620170746](https://github.com/murdercode/Nova4-TinymceEditor/assets/71822953/112b6202-6809-46bf-ba7f-6456ba81597e)

but in detail page I see another style

![iScreen Shoter - Google Chrome - 230620170832](https://github.com/murdercode/Nova4-TinymceEditor/assets/71822953/76109968-26ec-4012-b8df-25fed6ae79ca)

**Comment by murdercode** [comment]
As said in the official website: https://www.tiny.cloud/docs/plugins/opensource/codesample/

> By default, codesample uses http://prismjs.com/ to embed the code samples within the editor and works out of the box. That is, when a user copies valid code syntax into the editable area the code will be automatically formatted according to Prism default CSS rules.

As specific, prismjs is made use of for code syntax. You will probably be able to achieve the same result by adapting prismjs to your needs.
In any case, this is not a problem related to the TinyMCE package, so I am forced to close it.
