### ISSUE TITLE
Javascript filtered

### ISSUE THREAD

**Issue by Joemires** [murdercode/Nova4-TinymceEditor#17]
Hey
I noticed javascript codes are filtered when saving or rendering into the editor, how can I enable javascript usage in the editor

**Comment by murdercode** [comment]
I'm pretty sure Tiny goes and removes any javascript code by default, I don't think it's possible to do that without an ad hoc extension.

**Comment by Joemires** [comment]
> I'm pretty sure Tiny goes and removes any javascript code by default, I don't think it's possible to do that without an ad hoc extension.

 Tiny documentation shows that you can turn off the filter for some tags

**Comment by murdercode** [comment]
> > I'm pretty sure Tiny goes and removes any javascript code by default, I don't think it's possible to do that without an ad hoc extension.
> 
> Tiny documentation shows that you can turn off the filter for some tags

Can you link it? If it goes under settings, you can simply override your by publishing from `vendor:publish`

**Comment by Joemires** [comment]
![image](https://github.com/murdercode/Nova4-TinymceEditor/assets/34143261/26f85ea4-cd7f-4dc0-8621-4ae6b57bf1e6)
https://www.tiny.cloud/docs/tinymce/6/content-filtering/#protect

**Comment by Joemires** [comment]
I will try testing it out on my end and will send a PR if everything works fine

**Comment by murdercode** [comment]
Thanks mate! Here's the release: https://github.com/murdercode/Nova4-TinymceEditor/releases/tag/v1.2.0
Tested in local and works ;)
