### ISSUE TITLE
error with js and css

### ISSUE THREAD

**Issue by OsTheNeo** [murdercode/Nova4-TinymceEditor#2]
![Screen Shot 2022-07-01 at 5 57 05 PM](https://user-images.githubusercontent.com/5789902/176975916-842f52a3-a13f-4e37-9336-031945e40ad0.png)

**Comment by murdercode** [comment]
Can you publish the entire path of these assets? I'm pretty sure they are assets from the TinyMCE servers.
Have you made any changes to the config? Did you enter the API key?

**Comment by hoczeus** [comment]
OK I think I fount it. The copied file with the command:
looks like that: 

<?php

return [
        'init' => [
            'menubar' => false,
            'autoresize_bottom_margin' => 40,
            'branding' => false,
            'image_caption' => true,
            'paste_as_text' => true,
            'paste_word_valid_elements' => 'b,strong,i,em,h1,h2',
        ],
        'plugins' => [
            'advlist autolink lists link image imagetools media',
            'paste code wordcount autoresize table',
        ],
        'toolbar' => [
            'undo redo | formatselect forecolor backcolor |
                 bold italic underline strikethrough blockquote removeformat |
                 align bullist numlist outdent indent | link table media insertmedialibrary | code',
        ],
        'apiKey' => env('TINYMCE_API_KEY', ''),
];

After changing the pluginsline to
        'plugins' => [
            'anchor advlist autolink autoresize autosave code fullscreen link lists image imagetools media
            paste wordcount',
linke in your example the TinyEditor works.
It looks like the 2 values instead of one causes the problem.

**Comment by murdercode** [comment]
I'm pretty sure that the bug as been fixed with the new version (v1).
Please let me know if there's any other issues, thanks folks ;)
