### ISSUE TITLE
Use specific filesystem storage disk for image upload

### ISSUE THREAD

**Issue by WillyReyno** [murdercode/Nova4-TinymceEditor#22]
Hello and thank you for your awesome work on this package! 

I just updated to the latest version in order to get the image upload feature on the editor. However, I don't know if it's possible to upload images to a specific disk defined in Laravel's `config/filesystems.php`? 

For example, I'm working on a blog and would like to have my image hosted on my s3 bucket which is defined in my `config/filesystems.php`: 

```
<?php

return [
    'disks' => [
        // ...
        
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],
];

```

Is this possible yet? It would be very helpful as it would allow us to profit from CDN cache on the blog posts featuring images.

Thank you

**Comment by JmzTaylor** [comment]
A straightforward way to do this without changing this package is to extend Http/Controllers/TinyImageController.php and implement your own logic in the upload function.

**Comment by sutcliffe121** [comment]
> A straightforward way to do this without changing this package is to extend Http/Controllers/TinyImageController.php and implement your own logic in the upload function.

How do you do this, please?

I created a copy of Http/Controllers/TinyImageController.php in my App/Http/Controllers folder, and named it TinyImageControllerOverride.php

I made my changes to read the disk from a config entry, but my project doesn't seem to pick up the new controller, it still uses the vendor package controller. It's the first time I have tried to extend a vendor controller - I'm not sure where I'm going wrong.

![image](https://github.com/murdercode/Nova4-TinymceEditor/assets/33236577/3327de23-ee1c-4f1f-a7c8-b3ec3496c004)

Any help appreciated.

**Comment by sutcliffe121** [comment]
So I found a solution:

In my NovaServiceProvider, I used the bind method to switch out the controller. 

![image](https://github.com/murdercode/Nova4-TinymceEditor/assets/33236577/9e16a3d8-d5fd-4ed1-8e46-f2e9b33b9319)

**Comment by JmzTaylor** [comment]
This is what I ended up doing

```
class TinyImageController extends BaseTinyImageController
{
    public function upload(Request $request): JsonResponse
    {
        $validator = $this->validateRequest($request);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()]);
        }

        reset($_FILES);
        $temp = current($_FILES);
        if (is_uploaded_file($temp['tmp_name'])) {
            // Process the image mine returns full url as I am uploading to CDN
            return response()->json(['location' => $imageUrl]);
        } else {
            return response()->json(['error' => 'Failed to move uploaded file.']);
        }
    }
}
```

And then for the /upload route 
```
Route::post('/upload', [TinyImageController::class, 'upload'])->name('tinymce.upload')->middleware(TinymceMiddleware::class);
```

**Comment by Oskar-Mikael** [comment]
Wouldn't it just be a question of adding a config var of `disk`, which would replace the hardcoded `public` string in `TinyImageController`?
