### ISSUE TITLE
Support 3rd party Plugins

### ISSUE THREAD

**Issue by pramanikriju** [murdercode/Nova4-TinymceEditor#23]
I wanted to add a third-party bootstrap plugin - [TinyMCE Bootstrap Plugin](https://www.tinymce-bootstrap-plugin.com/)

It required me to add a custom object in the editor options, but it's not getting initialized 

```
 'bootstrapConfig' => [
                    'url' =>'bootstrap5/plugin/',
                    'iconFont' => 'fontawesome5',
                    'imagesPath' => '/assets/images',
                    'key' => config('services.tinymce_plugin_key')
                ],
```
Any ideas on how to add third party plugins, or any plans to include that in the documentation?

**Comment by murdercode** [comment]
there should be no problem, we also use the editor with external plugins

do we have a javascript log or something we can analyse? maybe it's just a formatting problem
