### ISSUE TITLE
Don't work with json fields :(

### ISSUE THREAD

**Issue by dprhmk** [murdercode/Nova4-TinymceEditor#26]
My code is :

      TinymceEditor::make('Content', 'data->main->text->en')
            ->fullWidth()
            
      or
      
      TinymceEditor::make('Text', 'data->text')
             ->fullWidth(),
             
![Знімок екрана 2024-05-23 о 10 48 05](https://github.com/murdercode/Nova4-TinymceEditor/assets/68992437/aaaa3388-0668-4940-9c8b-6106631cb125)

**Comment by davidelvir** [comment]
You can work around it by using ``resolveUsing`` and ``fileUsing``.
```
TinymceEditor::make('Text', 'text')
                ->resolveUsing(function ($value, $model) {
                    return $model->data['text'] ?? '';
                })->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
                    $data = $model->data;
                    $content[$attribute] = $request->input($attribute);
                    $model->data = $data;
                })
```
