### ISSUE TITLE
Package not shown as supporting Nova 4

### ISSUE THREAD

**Issue by mrleblanc101** [murdercode/Nova4-TinymceEditor#3]
Hi,
The package is not shown as supporting Nova 4 on https://novapackages.com/packages/murdercode/nova4-tinymce-editor
![Capture d’écran, le 2022-10-17 à 00 03 19](https://user-images.githubusercontent.com/17392251/196086845-d61d7cf1-0fbd-49a1-8fca-c78d06c7fcee.png)

**Comment by murdercode** [comment]
Hi, thanks for your message!
I'll fix it as soon as possible :)

**Comment by murdercode** [comment]
Fixed in v1.0.2
![Screenshot 2022-10-25 alle 10 12 16](https://user-images.githubusercontent.com/7630252/197720022-811f897c-961d-48d1-ae58-8d0bf3ebe8bf.png)
