### ISSUE TITLE
Question: Can I use this package with the API key on a free plan account ?

### ISSUE THREAD

**Issue by 0proboy0** [murdercode/Nova4-TinymceEditor#4]

**Comment by murdercode** [comment]
Sure!

**Comment by 0proboy0** [comment]
> Sure!

Awesome, thanks, I just didn't get it if the api key is just for the free trial or it's also for the free plan, thanks again.

**Comment by 0proboy0** [comment]
> The api is for free and paid plains

I got it, thank you.
