### ISSUE TITLE
Support for `whitecube/nova-flexible-content`

### ISSUE THREAD

**Issue by mbardelmeijer** [murdercode/Nova4-TinymceEditor#8]
Love the simplicity of the package and wish to use it on one of our projects.

We're running into an issue with https://github.com/whitecube/nova-flexible-content; when the content is reordered (i.e. rerendered), the tinyMCE field breaks. The content entered goes empty, and no content can be entered after. The toolbar does remain intact.

I've done some initial research but could not quickly find a solution.

**Comment by murdercode** [comment]
Tested and working with latest Flexible Content

![Screenshot 2023-06-16 alle 17 19 01](https://github.com/murdercode/Nova4-TinymceEditor/assets/7630252/a886612e-b92e-4c4c-bd07-d412d9f60f2f)

**Comment by skywalker666** [comment]
Hi there, since moving from flexible content to repeater fields in nova4, upon creating new models (it works for update) the second repeated element does not show the editor anymore (it's just a textarea). Should I open a new ticket and provide more information (it's pretty similar to this one)

**Comment by murdercode** [comment]
> Hi there, since moving from flexible content to repeater fields in nova4, upon creating new models (it works for update) the second repeated element does not show the editor anymore (it's just a textarea). Should I open a new ticket and provide more information (it's pretty similar to this one)

Thank you,
I honestly hadn't seen this field in the new updates yet. Yes, if you create a new ticket it is more convenient for everyone to see the problem and propose a fix (I'll see if I can do something in the next few days).
